name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch: # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync --dev

    - name: Run unit tests
      run: |
        uv run pytest tests/test_unit_*.py -v --cov=scripts --cov=workato_sdk_docs --cov-report=xml

    - name: Run integration tests
      run: |
        uv run pytest tests/test_integration_*.py -v --timeout=60
      continue-on-error: true # Integration tests might fail due to network issues

    - name: Run regression tests
      run: |
        uv run pytest tests/test_regression_*.py -v
      continue-on-error: true # Regression tests validate against live data

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.12'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  performance-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up uv
      uses: astral-sh/setup-uv@v3

    - name: Run performance tests
      run: |
        uv run pytest tests/test_performance.py -v --durations=10

  security-scan:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run security scan
      uses: securecodewarrior/github-action-sast@master
      with:
        api-key: ${{ secrets.SECURITY_SCAN_API_KEY }}
        project: workato-sdk-docs
      continue-on-error: true
